### ISSUE TITLE
Switch landing.html to Graham's DSTU 2 server

### ISSUE THREAD

**Issue by kpshek** [cerner/cardiac-risk-app#2]
Currently, the landing.html page is using the SMART Health IT FHIR server. However, this has the following drawbacks:

- It doesn't support `gt` date querying
- The test data doesn't have valueQuantity.code attributes (only valueQuantity.unit values)

Let's switch to Grahame Grieve's DSTU 2 server at http://fhir2.healthintersections.com.au/open. We'll still need to import test patients for our purposes, but this will be relatively easy and we'll have support for the `gt` date query filter.

**Comment by zplata** [comment]
@kpshek The query that existed for searching by `date` was used incorrectly. The date passed in with the `gt` originally specified a date **with** a time stamp, so the query "broke" when it tried to just find the month, day, and year. I can switch to use the `dateTime` query rather than `date` like we originally had it, if we want to (this allows the query to complete successfully).

**Comment by shriniketsarkar** [comment]
@zplata based off of http://hl7.org/fhir/dstu2/search.html#date the search parameter "date" can have dateTime which currently our fhir services support. We need to look for if these new server's support http://hl7.org/fhir/observation.html with the Search Parameters mentioned in the specs.

**Comment by zplata** [comment]
Yeah after looking into our spec and the fhir spec, makes more sense. Looks like the smarthealthit and grahame's server do not support `dateTime` "within" `date`, and we can look into being more specific with querying by `dateTime` possibly.

**Comment by zplata** [comment]
Update: On further investigation, even `dateTime` is not querying by the specified date. And trying to query `date` makes the lab query fail. But the new test data I have setup has a `valueQuantity.code` attribute, and that is working fine.

**Comment by zplata** [comment]
We can create patients in Grahames DSTU2 server as we need and add them to the patient listing page.
