### ISSUE TITLE
Automatically push to Github Pages via grunt task

### ISSUE THREAD

**Issue by kpshek** [cerner/cardiac-risk-app#6]
Rather than manually pushing content to the gh-pages branch, I'd like to do so via an automated grunt task.

https://github.com/tschaub/grunt-gh-pages looks promising, but we need to change how we're generating the build folder and js files (which would be a good change) in order to use this plugin.

**Comment by zplata** [comment]
Closed here: https://github.com/cerner/cardiac-risk-app/pull/22
